version: '3'

services:
  nacos:
    image: nacos/nacos-server:v2.2.3-slim
    container_name: saber-nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
      - "9848:9848"

  mysql:
    image: mysql:latest
    container_name: saber-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sipc@2023@saber
      - MYSQL_DATABASE=saber
    ports:
      - "3308:3306"
    volumes:
      - ./sql/saber.sql:/docker-entrypoint-initdb.d/saber.sql

  redis:
    image: redis:latest
    container_name: saber-redis
    environment:
      - REDIS_PASSWORD=sipc@2023@saber
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: saber-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=sipc@2023@saber
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:latest
    container_name: saber-mongodb
    ports:
      - "27017:27017"